//定义Action 类型

const ACTION_TYPES = {
    TODOLIST_VALUE_CHANGE:'TODOLIST_VALUE_CHANGE',
    TODOLIST_TODO_ITEM_ADD:'TODOLIST_TODO_ITEM_ADD',
    TODOLIST_TODO_ITEM_DELETE:'TODOLIST_TODO_ITEM_DELETE',
}

export default ACTION_TYPES;